backend:
  name: test-repo
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "docs"
    label: "ドキュメント"
    folder: "docs"
    create: true
    delete: true
    extension: "md"
    format: "frontmatter"
    fields:
      - {label: "タイトル", name: "title", widget: "string"}
      - {label: "説明", name: "description", widget: "text"}
      - {label: "スラッグ", name: "slug", widget: "string", required: false}
      - {label: "サイドバー", name: "sidebar_label", widget: "string", required: false}
      - {label: "本文", name: "body", widget: "markdown"} 